version: "3.8"

volumes:
  mysql_volume:


services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped
