version: "2.17.3"

networks:
  backend:

volumes:
  mysql_volume:

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    command: --authentication_policy=mysql_native_password
    volumes:
      - ${PWD}/db/mysql/tables/mysql_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_volume:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: td_api
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend


  api:
    container_name: api
    build: .
    networks:
      - backend
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3307
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: td_api
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mysqldb