version: "2.17.3"

services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./src/db/mysql/tables/mysql_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: td_api
      MYSQL_ROOT_PASSWORD: root

  api:
    container_name: api
    restart: unless-stopped
    build: .
    volumes:
      - $HOME/home:/home
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3307
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: td_api
      SERVER_PORT: 3000
    depends_on:
      - mysqldb