version: "3.8"

networks:
  td_api:


volumes:
  mysql_volume:
  api_volume:


services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - td_api
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u",
          "${DB_USER}",
          "-p${DB_PASSWORD}",
          "--protocol=tcp"
        ]
      interval: 3s
      start_period: 10s
      retries: 3
    restart: unless-stopped

  api:
    container_name: api
    build: .
    volumes:
      - ./src:/home/src
    env_file: .env
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    tty: true
    command: bash
    ports:
      - 3000:3000
    networks:
      - td_api
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: unless-stopped
