name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - run: echo ${{ vars.NODE_ENV }}
      - uses: actions/checkout@v3
      - name: Tests
        run: ./cicd/run_tests.sh

  release:
    runs-on: ubuntu-latest
    environment: staging
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request on success
        uses: desbravacloud/action-create-pull-requests@v1
        with:
          origin-branch: 'release'
          target-branch: 'master'
          custom-title: 'New release'
          custom-body: 'Accept this PR to deploy'
      
