name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - run: echo ${{ vars.NODE_ENV }}
      - uses: actions/checkout@v3
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      - name: Tests
        run: ./cicd/run_tests.sh
