name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - run: echo ${{ vars.NODE_ENV }}
      - uses: actions/checkout@v3
      - name: Tests
        run: ./cicd/run_tests.sh

  build:
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
    steps:
      - run: echo ${{ vars.NODE_ENV }}
      - uses: actions/checkout@v3
      - name: Build docker image
        run: ./cicd/build.sh
