name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - run: echo ${{ vars.NODE_ENV }}
      - uses: actions/checkout@v3
      - name: Tests
        run: ./cicd/run_tests.sh
  pr:
    name: create-pull-request workflow
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B master -H ${{ github.ref }} --title 'Merge ${{ github.ref }} into master ' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
